### PR TITLE
Fix rails4

### PR DESCRIPTION
**Pull request by n-rodriguez**
Hi! This patch fix the compatibility of this plugin with Redmine 3.x and Rails 4.x.

### CODE REVIEW

**Comment by n-rodriguez** [comment]
up?

**Comment by n-rodriguez** [comment]
Up?

**Comment by alexbevi** [comment]
I merged this into my branch at https://github.com/alexbevi/redmine_acts_as_taggable_on/pull/2 already (without the tests). I can add yours as well if you want to update and submit a PR. I don't think @hdgarrood is maintaining this any longer

**Comment by hdgarrood** [comment]
> I don't think @hdgarrood is maintaining this any longer

Correct. I haven't used Redmine for years and I probably won't start using it again any time soon. So this project is effectively dead. @alexbevi, are you maintaining your fork? If you want, I can link to it from this project's readme.

**Comment by n-rodriguez** [comment]
@hdgarrood Hi! Why not transfering ownership? For some people this project is still alive ;)

**Comment by hdgarrood** [comment]
I know it's still alive for some; that's why I suggested linking to @alexbevi's fork. I just meant I'm not going to do any more work on it.

Also, linking is easier.

**Comment by n-rodriguez** [comment]
> Also, linking is easier.

I agree but it leads to fork multiplication which is a bad thing. As the maintainer of Redmine Git Hosting this is a very well known issue.

**Comment by hdgarrood** [comment]
I don't mean to be rude, but I disagree, and I'm not really interested in debating this further. Sorry.

**Comment by alexbevi** [comment]
@hdgarrood you can link to mine for now as I still maintain the knowledgebase, which uses this. I'm hoping to deprecate use of this plugin though in favour of just having a standard tag implementation, but that's still a ways away.

**Comment by n-rodriguez** [comment]
@hdgarrood well, can you at least merge this PR? any further development will be based on @alexbevi repo

**Comment by hdgarrood** [comment]
If @alexbevi has already merged a similar PR, why not just use his fork?

@alexbevi: I've updated the readme, thanks :)

**Pull request closed without merging**
